export const mock_data = [
   {
      posterSrc: '/assets/poster3.jpg',
      title: 'Engaging UI/UX Design',
      price: '150000000',
      duration: '8 Weeks',
      rating: 5.0,
      _id: '345',
   },
   {
      posterSrc: '/assets/poster1.jpg',
      title: 'Social Media Marketing',
      price: '150000000',
      duration: '6 Weeks',
      rating: 4.5,
      _id: '345',
   },
   {
      posterSrc: '/assets/poster3.jpg',
      title: 'Engaging UI/UX Design',
      price: '150000000',
      duration: '8 Weeks',
      rating: 3.5,
      _id: '345',
   },
   {
      posterSrc: '/assets/poster4.png',
      title: 'Social Media Marketing',
      price: '150000000',
      duration: '6 Weeks',
      rating: 2.5,
      _id: '345',
   },
   {
      posterSrc: '/assets/poster3.jpg',
      title: 'Engaging UI/UX Design',
      price: '150000000',
      duration: '8 Weeks',
      rating: 6,
      _id: '345',
   },
   {
      posterSrc: '/assets/poster4.png',
      title: 'Social Media Marketing',
      price: '150000000',
      duration: '6 Weeks',
      rating: 4.5,
      _id: '345',
   },
];
