import './globals.css';
import type { Metadata, Viewport } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

const geistSans = Geist({
   variable: '--font-geist-sans',
   subsets: ['latin'],
});

const geistMono = Geist_Mono({
   variable: '--font-geist-mono',
   subsets: ['latin'],
});

export const metadata: Metadata = {
   title: 'Skill Bridge',
   manifest: '/manifest.json',
   description: 'Generated by create next app',
   icons: {
      icon: '/assets/logo.png',
   },
};

export const viewport: Viewport = {
   maximumScale: 1,
   userScalable: false,
   viewportFit: 'auto',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <head>
            <link rel="manifest" href="/manifest.json" />
            <link rel="apple-touch-icon" href="/assets/logo.png" />
            <link
               rel="apple-touch-icon"
               sizes="512x512"
               href="/assets/logo.png"
            />
            <meta name="theme-color" content="#0f172a" />
            <meta name="apple-mobile-web-app-capable" content="yes" />
            <meta
               name="apple-mobile-web-app-status-bar-style"
               content="default"
            />
         </head>

         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased `}
         >
            {children}
         </body>
      </html>
   );
}
